### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by tea-lemon-balm** [codestates/mellowboard#15]
# Todo List

## **1. 시스템 아키텍처**

- [ ]  JWT를 이용한 로그인 구현 | 필수 | ★
- [ ]  권한 부여(Authorization)에 따른 기능의 접근 제한 구현 (예- 일반 사용자, 관리자 권한) | 필수 | ★
- 인증 미들웨어 구현 - 2h - server
- 각 필요한 라우터에 적용하기 - 30m

## **2. UI/UX**

- [ ]  회원가입, 로그인, 로그아웃, 마이페이지, 회원탈퇴 기능 구현 | 필수 | 프론트엔드, 백엔드 | ★
- [ ]  회원가입, 로그인 및 회원정보 수정 시 유효성 검사 | 필수 | 프론트엔드 | ★
- [ ]  소셜 로그인 외 서비스 자체 회원가입 기능 제공 | 필수 | 프론트엔드 | ★
- [ ]  회원가입 없이 '체험하기' 형식으로 가볍게 기능을 이용할 수 있는 장치 마련 - 비 회원이 게시글, 댓글조회 가능 | 필수(Final only) | 프론트엔드 | ★
- [ ]  마이페이지를 통해 사용자 개인정보 수정 기능 제공 | 필수 | 프론트엔드 | ★
- [ ]  (소셜 로그인이 아닐 경우) 비밀번호 수정 기능 제공 | 필수 | 프론트엔드 | ★
- [ ]  라이브러리를 사용하지 않고 React 컴포넌트 직접 작성 (유어클래스에서 다룬 것) | 필수 | ★
- [ ]  무한 스크롤 | 필수 | ★
- [ ]  게시글 페이지 만들기  | 필수 | ★
- [ ]  게시글 CRUD에서 해시태그도 같이 | 필수 | ★
- [ ]  댓글 확장 기능 | 필수 | ★
- [ ]  배경사진 골라서 React 안에 하드코딩 | 필수 | ★
- [ ]  모바일 / 데스크탑 반응형 디자인 | 필수 | ★
- [ ]  테블릿 반응형 디자인 | 권장 | ★★
- [ ]  검색을 위한 컴포넌트 개발 | 권장 | ★★
- [ ]  배경사진 커스텀 업로드기능 | 권장 | ★★
    - 글 작성시 파일업로드 기능
    - axios요청시 파일 전송 방식 서버와 맞추기..
- [ ]  게시글 페이지에 좋아요, 싫어요, 신고, 북마크 기능 추가 | 도전 | ★★★
    - 마이페이지에 북마크탭 추가
- [ ]  좋아요/댓글 순으로 정렬하는 기능 | 도전 | ★★★
    - 추가 정렬을 위한 버튼 만들기
    - axios 게시글 조회 다시 연동하기
- [ ]  게시글 작성시 GIF 업로드 기능 | 도전 | ★★★
- [ ]  비밀댓글 기능 | 신중 | ★★★★
- [ ]  회원가입 OAuth | 신중 | ★★★★
- [ ]  이모지 단축 기능 | 신중 | ★★★★

## **3. 스키마 및 API**

- [ ]  N:M (다대다) - 해시태그 관계 설정 | 필수 | ★
- [ ]  ERD (DB Diagram) 작성 | 필수 | ★
- [ ]  API 작성 툴 (Swagger, Postman, Gitbook API) 사용 | 필수 | ★★
- [ ]  ORM 사용 (sequelize, typeorm 권장) | 권장 | ★
- [ ]  페이지네이션 구현 | 권장 | ★★★
- [ ]  게시글 및 댓글 정렬기능
- [ ]  해시태그를 이용한 게시물 조회 API | 권장 | ★★
- [ ]  검색을 위한 스키마 조정 및 인덱싱 | 권장 | ★★
- [ ]  배경사진 저장을 위한 S3생성 및 AWS SDK연동 | 권장 | ★★
- [ ]  좋아요 싫어요,신고, 북마크 기능 추가 | 권장 |★★
    - 스키마 추가하기
    - API 구현하기
    - 게시글 조회 API  수정하기 (좋아요 등, 데이터 포함)
- [ ]  게시글 좋아요, 댓글 순 정렬 추가 | 권장 | ★★
- [ ]  GIF 업로드 기능추가 | 권장  | ★
    - S3연동
- [ ]  비밀댓글 기능 | 신중 | ★★★★
- [ ]  OAuth 회원가입 기능 | 신중 | ★★★★
- [ ]  회원 이메일 인증 기능 | 신중 | ★★★★

## **4. DevOps**

- [ ]  [코드] precommit 단계에서 semistandard 적용 | 필수 | 프론트, 백엔드 |★
- [ ]  [릴리즈] 깃허브 커밋메세지 규칙 합의 | 필수  | 프론트, 백엔드  | ★
- [ ]  [코드] 버전 규칙 합의 | 필수 | 프론트, 백엔드  | ★
- [ ]  [릴리즈] PR 형식 합의 | 권장 | 프론트, 백엔드  | ★
- [ ]  [배포] AWS 구축 | 필수 | ★
- [ ]  CI/CD Jenkins 구축 | 필수 | ★
- [ ]  도메인 구매 및 https 구축 | 필수 | ★
- [ ]  ESLint 컨벤션 통일 | 필수 | 프론트, 백엔드  | ★
- [ ]  초기 개발환경 구축 | 필수 | 프론트, 백엔드  | ★
- [ ]  백엔드 테스트 코드 작성 | 권장 | ★★★
- [ ]  [코드] Docker를 이용한 개발환경 구축 및 전 팀원의 이용 |도전 | ★★★
