### ISSUE TITLE
전체 페이지 - 헤더 목업 디자인

### ISSUE THREAD

**Issue by junghoonme** [codestates/mellowboard#16]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: main page - header mock-up design

### TODO
1. [x] 헤더 목업 디자인
2. [x] 헤더 모바일 반응형 디자인
3. [x] 헤더 데스크탑 반응형 디자인

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `Middle`
