### ISSUE TITLE
게시글 페이지 - 게시판 조회 목업 디자인

### ISSUE THREAD

**Issue by junghoonme** [codestates/mellowboard#17]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: main page - board read mock-up design

### TODO
1. [x] 게시판 첫 화면 조회 상태 목업 디자인
2. [ ] 모바일 반응형 디자인
3. [ ] 데스크탑 반응형 디자인

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `Middle`
