### ISSUE TITLE
게시글  페이지 - 게시판 수정 상태 디자인 목업

### ISSUE THREAD

**Issue by junghoonme** [codestates/mellowboard#18]
### ISSUE
- Group:  `client`
- Type: feature`
- Detail: main page - modify state mock-up design

### TODO
1. [x] 게시글 페이지 - 게시판 수정 상태 UI 목업 디자인하기
2. [ ] 모바일 반응형 디자인
3. [ ] 데스크탑 반응형 디자인

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `Middle`
