### ISSUE TITLE
AWS 구축

### ISSUE THREAD

**Issue by tea-lemon-balm** [codestates/mellowboard#21]
### ISSUE
- Group:  `server`
- Detail: 배포 환경 구축

### TODO
1. [ ] [배포] AWS 구축 | 필수 | ★ - 1h
2. [ ] AWS IAM User, EC2, RDS 만들기 - 1h
3. [ ] 도메인 구매 route 53 및 ELB 설정 및 https적용

### Estimated time
> Pick one

### Labels
- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint2`
- Urgency: `High`
