### ISSUE TITLE
마이 페이지 - tab 목업 디자인 구현

### ISSUE THREAD

**Issue by junghoonme** [codestates/mellowboard#22]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: mypage - tab mock-up design

### TODO
1. [x] 마이 페이지 - 탭 목업 디자인
2. [ ] 모바일 반응형 디자인
3. [x] 데스크탑 반응형 디자인

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `client`, `server`
- Sprint: `Sprint 2`
- Urgency: `Middle`
