### ISSUE TITLE
DB작성, API 문서 작성

### ISSUE THREAD

**Issue by tea-lemon-balm** [codestates/mellowboard#24]
### ISSUE
- Group:  `sr`

### TODO
1. [x] N:M (다대다) - 해시태그 관계 설정 | 필수 | ★
2. [x] ERD (DB Diagram) 작성 | 필수 | ★
3. [x] API 작성 툴 (Swagger, Postman, Gitbook API) 사용 | 필수 | ★★

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `server`
- Sprint: `Sprint1`
- Urgency: `High`
