### ISSUE TITLE
회원가입, 로그인, 로그아웃, 마이페이지, 회원탈퇴 API 구현

### ISSUE THREAD

**Issue by tea-lemon-balm** [codestates/mellowboard#25]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [ ] 회원가입, 로그인, 로그아웃, 마이페이지, 회원탈퇴 API 구현 | 필수 |  백엔드 | ★
2. [ ] 회원가입, 로그인,로그아웃 API 구현
3. [ ] 회원정보 조회, 수정, 탈퇴 API 구현

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`, `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`, `Middle`, `Low`
