### ISSUE TITLE
마이페이지 - Tab1: 내가 작성한 글 목업 디자인

### ISSUE THREAD

**Issue by junghoonme** [codestates/mellowboard#27]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: mypage - Tab1: 내가 작성한 글 mock-up design
### TODO
1. [x] 마이페이지 - 내가 작성한 글 목업 디자인하기
2. [ ] 모바일 반응형 디자인
3. [x] 데스크탑 반응형 디자인

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `Middle`
