### ISSUE TITLE
글 작성 모달 목업 디자인

### ISSUE THREAD

**Issue by junghoonme** [codestates/mellowboard#36]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 글 작성 modal mock-up design

### TODO
1. [ ] 글 모달 목업 디자인 구현하기
2. [ ] 모바일 반응형 디자인 
3. [ ] 데스크탑 반응형 디자인 

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `Middle`
