### ISSUE TITLE
마이페이지 - 내 정보 조회 및 수정 및 탈퇴

### ISSUE THREAD

**Issue by junghoonme** [codestates/mellowboard#46]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 마이페이지 - 내 정보 조회 및 수정 및 탈퇴 기능 구현
-
### TODO
1. [ ] 내 정보 조회 기능
2. [ ] 내 정보 수정 기능
3. [ ] 내 정보 탈퇴 기능
4. [ ] 유효성 검사

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint_3`
- Urgency: `Middle`
